package com.edwin;


import java.util.Random;
import java.util.Scanner;

public class Main {
   // public static int row=0, col=0;
   public static int [][]answer = new int [100][5];
   public static int count=0;
   public static void printQuestionResult() {
       //ans[i][0] type
       //ans[i][1] x
       //ans[i][2] y
       //ans[i][3] result
       //ans[i][4] ans


       System.out.println("The question generated by the system are:");
       int correct=0,wrong=0;
       System.out.println("count final: "+ count);
       for (int i = 0; i < count-1; i ++) {//count-1 because the question we input -1 so shouldnt count

           System.out.print(answer[i][1]);
           operator(i);
           System.out.print(answer[i][2] + " = " + answer[i][3]);

           if (answer[i][3]==answer[i][4]) {
               System.out.println("");
               correct++;
           }
           else{
               wrong++;
               System.out.println(" Your answer was " + answer[i] [4]+ " which was incorrect");
           }

       }
       System.out.println("---------------------------------------------");
       System.out.printf("You got %s correct and %s wrong", correct, wrong);
   }
   public static void operator(int index){
       switch (answer[index][0]){
           case 1:
               System.out.print(" + ");
           break;
           case 2: System.out.print(" - ");
               break;
           case 3: System.out.print(" x ");
               break;
           case 4: System.out.print(" / ");
               break;
           default:
               System.out.println(index);

       }
   }
    public static void main(String[] var0) {

        Random r = new Random();
        Addition a = new Addition();
        Subtraction s = new Subtraction();
        Multiply3 m = new Multiply3();
        Divison d = new Divison();
        Scanner scanner = new Scanner(System.in);
        int ans=0;
        do{
            int type = r.nextInt(4);
            switch (type){
                case 0:
                    int temp[]=a.quiz();
                    for(int i=0; i<5;i++)
                    {
                        answer[count][i]=temp[i];
                    }

                    ans = scanner.nextInt();
                    a.checkResponse(ans);
                    answer[count++][4]=ans;
                    break;
                case 1: int temp1[]=s.quiz();
                    for(int i=0; i<5;i++)
                    {
                        answer[count][i]=temp1[i];
                    }
                    //Scanner scanner = new Scanner(System.in);
                    ans = scanner.nextInt();
                    s.checkResponse(ans);
                    answer[count++][4]=ans;
                    break;
                case 2:
                    int temp2[]=m.quiz();
                    for(int i=0; i<5;i++)
                    {
                        answer[count][i]=temp2[i];
                    }
                    //Scanner scanner = new Scanner(System.in);
                    ans = scanner.nextInt();
                    m.checkResponse(ans);
                    answer[count++][4]=ans;
                    break;
                case 3: int temp3[]=d.quiz();
                    for(int i=0; i<5;i++)
                    {
                        answer[count][i]=temp3[i];
                    }
                    //Scanner scanner = new Scanner(System.in);
                    ans = scanner.nextInt();
                    d.checkResponse(ans);
                    answer[count++][4]=ans;
                    break;
                default:
                    System.out.println("error");

            }
        }while(ans!=-1);
        printQuestionResult();

    }
}
